/* Pexip Universal Library for Secure Engagement.
 *
 * Copyright (C) 2022 Pexip AS
 * @author Knut Saastad
 * @author Tulio Beloqui
 */

#ifndef _PULSE_EVENTS_H_
#define _PULSE_EVENTS_H_

/**
 * @brief Conference event types.
 * Defines the types of events that can be received from a conference session.
 */
typedef enum
{
  PULSE_CONFERENCE_EVENT_TYPE_HELLO,
  PULSE_CONFERENCE_EVENT_TYPE_BYE,
  PULSE_CONFERENCE_EVENT_TYPE_PRESENTATION_START,
  PULSE_CONFERENCE_EVENT_TYPE_PRESENTATION_STOP,
  PULSE_CONFERENCE_EVENT_TYPE_PRESENTATION_FRAME,
  PULSE_CONFERENCE_EVENT_TYPE_PRESENTATION_FRAME_RESET,
  PULSE_CONFERENCE_EVENT_TYPE_PARTICIPANT_CREATE,
  PULSE_CONFERENCE_EVENT_TYPE_PARTICIPANT_UPDATE,
  PULSE_CONFERENCE_EVENT_TYPE_PARTICIPANT_DELETE,
  PULSE_CONFERENCE_EVENT_TYPE_PARTICIPANT_SYNC_BEGIN,
  PULSE_CONFERENCE_EVENT_TYPE_PARTICIPANT_SYNC_END,
  PULSE_CONFERENCE_EVENT_TYPE_CONFERENCE_UPDATE,
  PULSE_CONFERENCE_EVENT_TYPE_LAYOUT,
  PULSE_CONFERENCE_EVENT_TYPE_MESSAGE_RECEIVED,
  PULSE_CONFERENCE_EVENT_TYPE_STAGE,
  PULSE_CONFERENCE_EVENT_TYPE_CALL_DISCONNECTED,
  PULSE_CONFERENCE_EVENT_TYPE_DISCONNECT,
  PULSE_CONFERENCE_EVENT_TYPE_FECC,
  PULSE_CONFERENCE_EVENT_TYPE_UPDATE_SDP,
  PULSE_CONFERENCE_EVENT_TYPE_NEW_OFFER,
  PULSE_CONFERENCE_EVENT_TYPE_NEW_CANDIDATE,
  PULSE_CONFERENCE_EVENT_TYPE_REFER,
  PULSE_CONFERENCE_EVENT_TYPE_REFER_CANCEL,
  PULSE_CONFERENCE_EVENT_TYPE_SPLASH_SCREEN,
  PULSE_CONFERENCE_EVENT_TYPE_PEER_DISCONNECT,
  PULSE_CONFERENCE_EVENT_TYPE_LIVE_CAPTIONS,
  PULSE_CONFERENCE_EVENT_TYPE_BREAKOUT_BEGIN,
  PULSE_CONFERENCE_EVENT_TYPE_BREAKOUT_EVENT,
  PULSE_CONFERENCE_EVENT_TYPE_BREAKOUT_END,
  PULSE_CONFERENCE_EVENT_TYPE_BREAKOUT_REFER,
  PULSE_CONFERENCE_EVENT_TYPE_BREAKOUT_REFER_CANCEL,
  PULSE_CONFERENCE_EVENT_TYPE_REFRESH_TOKEN,
  __PULSE_CONFERENCE_EVENT_TYPE_SIZE__
} PulseConferenceEventType;

#endif /* _PULSE_EVENTS_H_ */